/******************************************************************************/
/*            Generated by IBExpert 2024.4.7.1 29/05/2024 13:52:50            */
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

SET CLIENTLIB 'C:\Windows\SysWOW64\fbclient.dll';

CREATE DATABASE 'Brabo/3051:E:\Projeto\brincar\banco\PONTO.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET NONE COLLATION NONE;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE FUNCIONARIO (
    ID     INTEGER GENERATED BY DEFAULT AS IDENTITY,
    NOME   VARCHAR(50) CHARACTER SET WIN1252 NOT NULL COLLATE WIN_PTBR,
    SENHA  VARCHAR(90) CHARACTER SET WIN1252 NOT NULL COLLATE WIN_PTBR,
    EMAIL  VARCHAR(50) NOT NULL
);

CREATE TABLE HORAS (
    ID              INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ID_FUNCIONARIO  INTEGER NOT NULL,
    DATA            DATE NOT NULL,
    HORA1           TIME NOT NULL,
    HORA2           TIME,
    HORA3           TIME,
    HORA4           TIME
);



/******************************************************************************/
/*                                   Views                                    */
/******************************************************************************/


/* View: CONSULTA_GRAFICO */
CREATE VIEW CONSULTA_GRAFICO(
    "Data",
    "Funcionário",
    "Hora 1",
    "Hora 2",
    "Hora 3",
    "Hora 4",
    "Total/Dia")
AS
SELECT 
    H.DATA AS "Data",
    F.NOME AS "Funcionário",
    H.HORA1 AS "Hora 1",
    H.HORA2 AS "Hora 2",
    H.HORA3 AS "Hora 3",
    H.HORA4 AS "Hora 4",
    CAST(
        (DATEDIFF(MINUTE, hora1, hora2) + DATEDIFF(MINUTE, hora3, hora4)) / 60.0 
    AS DECIMAL(10,2)) AS "Total/Dia"
FROM
    HORAS H
JOIN 
    FUNCIONARIO F ON H.ID_FUNCIONARIO = F.ID
;



/* View: CONSULTA_PONTOS */
CREATE VIEW CONSULTA_PONTOS(
    "Data",
    "Funcionário",
    "Hora 1",
    "Hora 2",
    "Hora 3",
    "Hora 4",
    "Total/Dia")
AS
SELECT 
    H.DATA AS "Data",
    F.NOME AS "Funcionário",
    H.HORA1 AS "Hora 1",
    H.HORA2 AS "Hora 2",
    H.HORA3 AS "Hora 3",
    H.HORA4 AS "Hora 4",
    CAST(FLOOR((DATEDIFF(SECOND, H.HORA1, H.HORA2) + DATEDIFF(SECOND, H.HORA3, H.HORA4)) / 3600) AS VARCHAR(2)) || ':' || 
    RIGHT('0' || CAST(FLOOR(MOD((DATEDIFF(SECOND, H.HORA1, H.HORA2) + DATEDIFF(SECOND, H.HORA3, H.HORA4)), 3600) / 60) AS VARCHAR(2)), 2) || ':' || 
    RIGHT('0' || CAST(MOD((DATEDIFF(SECOND, H.HORA1, H.HORA2) + DATEDIFF(SECOND, H.HORA3, H.HORA4)), 60) AS VARCHAR(2)), 2) AS "Total/Dia"

FROM
    HORAS H
JOIN 
    FUNCIONARIO F ON H.ID_FUNCIONARIO = F.ID
;




/******************************************************************************/
/*                          Autoincrement generators                          */
/******************************************************************************/

ALTER TABLE FUNCIONARIO ALTER ID RESTART WITH 0;
ALTER TABLE HORAS ALTER ID RESTART WITH 41;




/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE FUNCIONARIO ADD CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (ID);
ALTER TABLE HORAS ADD PRIMARY KEY (ID);


/******************************************************************************/
/*                                Foreign keys                                */
/******************************************************************************/

ALTER TABLE HORAS ADD CONSTRAINT FK_HORAS_1 FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO (ID);


/******************************************************************************/
/*                                   Roles                                    */
/******************************************************************************/

CREATE ROLE RDB$ADMIN;
